### ISSUE TITLE
'/data/project/rw/rung/model/roberta-large/', what is this route?

### ISSUE THREAD

**Issue by sdlee130** [rungjoo/Emotion_not_One#1]
Hi. I'm going to read this paper and clone and run this repository.

```
roberta_tokenizer = RobertaTokenizer.from_pretrained('/data/project/rw/rung/model/roberta-large/') 
```
An error occurred while executing the above code.
```
HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/project/rw/rung/model/roberta-large/'. Use `repo_type` argument if needed.
```

I think I can solve it if I modify the path. The path written in the error code could not be found. How should I modify it?

**Comment by rungjoo** [comment]
Thanks for pointing out the error.
/data/project/rw/rung/model/roberta-large/ is the personal path where the model was downloaded from huggingface.

For example in [code](https://github.com/rungjoo/Emotion_not_One/blob/master/self_teacher/model.py#L21)
- **Just delete line 21 and use line 22.**
- Or you can directly change the path to "roberta-large".

**Comment by sdlee130** [comment]
Thanks to you, I've solved this issue.
